"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Loader2, Download, Copy, Sparkles, FileText } from "lucide-react"

interface FormData {
  noticeType: string
  senderName: string
  senderAddress: string
  recipientName: string
  recipientAddress: string
  scenario: string
  urgency: string
  additionalDetails: string
}

export function LegalNoticeGenerator() {
  const [formData, setFormData] = useState<FormData>({
    noticeType: "",
    senderName: "",
    senderAddress: "",
    recipientName: "",
    recipientAddress: "",
    scenario: "",
    urgency: "normal",
    additionalDetails: "",
  })
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedNotice, setGeneratedNotice] = useState("")
  const [showPreview, setShowPreview] = useState(false)

  const handleInputChange = (field: keyof FormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  const generateNotice = async () => {
    setIsGenerating(true)
    setShowPreview(false)

    // Simulate AI generation delay
    await new Promise((resolve) => setTimeout(resolve, 3000))

    // Generate mock legal notice based on form data
    const notice = generateMockNotice(formData)
    setGeneratedNotice(notice)
    setShowPreview(true)
    setIsGenerating(false)
  }

  const generateMockNotice = (data: FormData): string => {
    const currentDate = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })

    return `LEGAL NOTICE

Date: ${currentDate}

TO: ${data.recipientName}
ADDRESS: ${data.recipientAddress}

FROM: ${data.senderName}
ADDRESS: ${data.senderAddress}

RE: ${getNoticeTitle(data.noticeType)}

Dear ${data.recipientName},

${getNoticeBody(data)}

This notice is served upon you for the following reasons:

${data.scenario}

${data.additionalDetails ? `Additional Details: ${data.additionalDetails}` : ""}

You are hereby required to take appropriate action within the timeframe specified by applicable law. Failure to comply with this notice may result in further legal action being taken against you.

${getUrgencyClause(data.urgency)}

This notice is served in accordance with applicable laws and regulations. If you have any questions regarding this notice, please contact the undersigned immediately.

Sincerely,

${data.senderName}

---
This document was generated by LegalMind. Please review carefully and consult with a qualified attorney before use.`
  }

  const getNoticeTitle = (type: string): string => {
    const titles: Record<string, string> = {
      eviction: "Notice to Quit and Demand for Possession",
      demand: "Demand Letter for Payment",
      cease: "Cease and Desist Notice",
      breach: "Notice of Breach of Contract",
      termination: "Notice of Termination",
      default: "Legal Notice",
    }
    return titles[type] || titles.default
  }

  const getNoticeBody = (data: FormData): string => {
    const bodies: Record<string, string> = {
      eviction: "You are hereby notified that your tenancy of the above-described premises is hereby terminated.",
      demand: "You are hereby demanded to pay the sum owed as detailed below.",
      cease: "You are hereby demanded to cease and desist from the activities described herein.",
      breach: "You are hereby notified that you are in breach of your contractual obligations.",
      termination: "You are hereby notified of the termination of our agreement.",
      default: "You are hereby notified of the following matter requiring your immediate attention.",
    }
    return bodies[data.noticeType] || bodies.default
  }

  const getUrgencyClause = (urgency: string): string => {
    const clauses: Record<string, string> = {
      urgent: "URGENT: Immediate action is required. Please respond within 24 hours.",
      normal: "Please respond within 30 days of receipt of this notice.",
      flexible: "Please respond at your earliest convenience, but no later than 60 days.",
    }
    return clauses[urgency] || clauses.normal
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedNotice)
  }

  const downloadNotice = () => {
    const element = document.createElement("a")
    const file = new Blob([generatedNotice], { type: "text/plain" })
    element.href = URL.createObjectURL(file)
    element.download = `legal-notice-${Date.now()}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="grid lg:grid-cols-2 gap-8">
      {/* Form Section */}
      <Card className="bg-card border-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-card-foreground font-montserrat">
            <FileText className="h-5 w-5 text-accent" />
            Notice Details
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="noticeType" className="text-card-foreground font-medium">
              Type of Legal Notice
            </Label>
            <Select value={formData.noticeType} onValueChange={(value) => handleInputChange("noticeType", value)}>
              <SelectTrigger className="bg-input border-border text-card-foreground">
                <SelectValue placeholder="Select notice type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="eviction">Eviction Notice</SelectItem>
                <SelectItem value="demand">Demand Letter</SelectItem>
                <SelectItem value="cease">Cease and Desist</SelectItem>
                <SelectItem value="breach">Breach of Contract</SelectItem>
                <SelectItem value="termination">Termination Notice</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="senderName" className="text-card-foreground font-medium">
                Your Name
              </Label>
              <Input
                id="senderName"
                value={formData.senderName}
                onChange={(e) => handleInputChange("senderName", e.target.value)}
                className="bg-input border-border text-card-foreground"
                placeholder="John Doe"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="recipientName" className="text-card-foreground font-medium">
                Recipient Name
              </Label>
              <Input
                id="recipientName"
                value={formData.recipientName}
                onChange={(e) => handleInputChange("recipientName", e.target.value)}
                className="bg-input border-border text-card-foreground"
                placeholder="Jane Smith"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="senderAddress" className="text-card-foreground font-medium">
              Your Address
            </Label>
            <Textarea
              id="senderAddress"
              value={formData.senderAddress}
              onChange={(e) => handleInputChange("senderAddress", e.target.value)}
              className="bg-input border-border text-card-foreground"
              placeholder="123 Main St, City, State 12345"
              rows={2}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="recipientAddress" className="text-card-foreground font-medium">
              Recipient Address
            </Label>
            <Textarea
              id="recipientAddress"
              value={formData.recipientAddress}
              onChange={(e) => handleInputChange("recipientAddress", e.target.value)}
              className="bg-input border-border text-card-foreground"
              placeholder="456 Oak Ave, City, State 67890"
              rows={2}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="scenario" className="text-card-foreground font-medium">
              Describe Your Situation
            </Label>
            <Textarea
              id="scenario"
              value={formData.scenario}
              onChange={(e) => handleInputChange("scenario", e.target.value)}
              className="bg-input border-border text-card-foreground"
              placeholder="Provide detailed information about the situation that requires a legal notice..."
              rows={4}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="urgency" className="text-card-foreground font-medium">
              Urgency Level
            </Label>
            <Select value={formData.urgency} onValueChange={(value) => handleInputChange("urgency", value)}>
              <SelectTrigger className="bg-input border-border text-card-foreground">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="urgent">Urgent (24 hours)</SelectItem>
                <SelectItem value="normal">Normal (30 days)</SelectItem>
                <SelectItem value="flexible">Flexible (60 days)</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="additionalDetails" className="text-card-foreground font-medium">
              Additional Details (Optional)
            </Label>
            <Textarea
              id="additionalDetails"
              value={formData.additionalDetails}
              onChange={(e) => handleInputChange("additionalDetails", e.target.value)}
              className="bg-input border-border text-card-foreground"
              placeholder="Any additional information or specific requirements..."
              rows={3}
            />
          </div>

          <Button
            onClick={generateNotice}
            disabled={isGenerating || !formData.noticeType || !formData.scenario}
            className="w-full bg-accent hover:bg-accent/90 text-accent-foreground font-semibold py-3"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating Notice...
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                Generate Legal Notice
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Preview Section */}
      <Card className="bg-card border-border">
        <CardHeader>
          <CardTitle className="flex items-center justify-between text-card-foreground font-montserrat">
            <span className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-accent" />
              Generated Notice
            </span>
            {showPreview && (
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={copyToClipboard} className="border-border bg-transparent">
                  <Copy className="h-4 w-4" />
                </Button>
                <Button variant="outline" size="sm" onClick={downloadNotice} className="border-border bg-transparent">
                  <Download className="h-4 w-4" />
                </Button>
              </div>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {!showPreview && !isGenerating && (
            <div className="flex flex-col items-center justify-center h-96 text-center">
              <div className="bg-accent/10 p-4 rounded-lg mb-4">
                <FileText className="h-12 w-12 text-accent" />
              </div>
              <h3 className="font-montserrat font-semibold text-lg text-card-foreground mb-2">Ready to Generate</h3>
              <p className="text-muted-foreground">
                Fill out the form and click "Generate Legal Notice" to create your document.
              </p>
            </div>
          )}

          {isGenerating && (
            <div className="flex flex-col items-center justify-center h-96 text-center">
              <div className="bg-accent/10 p-4 rounded-lg mb-4">
                <Loader2 className="h-12 w-12 text-accent animate-spin" />
              </div>
              <h3 className="font-montserrat font-semibold text-lg text-card-foreground mb-2">
                Generating Your Notice
              </h3>
              <p className="text-muted-foreground">Our AI is crafting a professional legal notice for you...</p>
            </div>
          )}

          {showPreview && (
            <div className="space-y-4">
              <div className="bg-input border border-border rounded-lg p-6">
                <pre className="whitespace-pre-wrap text-sm text-card-foreground font-mono leading-relaxed">
                  {generatedNotice}
                </pre>
              </div>
              <div className="flex gap-2">
                <Button onClick={copyToClipboard} variant="outline" className="flex-1 border-border bg-transparent">
                  <Copy className="mr-2 h-4 w-4" />
                  Copy to Clipboard
                </Button>
                <Button onClick={downloadNotice} className="flex-1 bg-accent hover:bg-accent/90 text-accent-foreground">
                  <Download className="mr-2 h-4 w-4" />
                  Download Notice
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
