import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { AlertTriangle } from "lucide-react"

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-1 py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-3 mb-8">
              <AlertTriangle className="h-8 w-8 text-primary" />
              <h1 className="text-4xl font-bold text-foreground">Legal Disclaimer</h1>
            </div>

            <div className="bg-muted/30 border-l-4 border-primary p-6 mb-8">
              <p className="text-lg font-semibold text-foreground mb-2">Important Notice</p>
              <p className="text-muted-foreground">
                This disclaimer is crucial to understand before using our legal notice generation service. Please read
                carefully.
              </p>
            </div>

            <div className="prose prose-lg max-w-none">
              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">No Attorney-Client Relationship</h2>
                <p className="text-muted-foreground">
                  The use of LegalNotice Pro does not create an attorney-client relationship between you and our company
                  or any affiliated legal professionals. We are not a law firm and do not provide legal representation
                  or advice.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">Not Legal Advice</h2>
                <p className="text-muted-foreground mb-4">The information and documents generated by our service:</p>
                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                  <li>Are not legal advice or legal opinions</li>
                  <li>Should not be relied upon as legal advice</li>
                  <li>Cannot replace consultation with a qualified attorney</li>
                  <li>May not be suitable for your specific legal situation</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  Professional Legal Consultation Required
                </h2>
                <p className="text-muted-foreground mb-4">We strongly recommend that you:</p>
                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                  <li>Consult with a qualified attorney before using any generated documents</li>
                  <li>Have all legal notices reviewed by legal counsel</li>
                  <li>Seek professional advice for complex legal matters</li>
                  <li>Understand the legal implications of serving legal notices</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">Accuracy and Completeness</h2>
                <p className="text-muted-foreground">
                  While we strive to provide accurate and up-to-date templates, we make no warranties or representations
                  about the accuracy, completeness, or suitability of our generated documents. Laws vary by jurisdiction
                  and change frequently.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">User Responsibility</h2>
                <p className="text-muted-foreground mb-4">You are solely responsible for:</p>
                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                  <li>Ensuring the accuracy of information you provide</li>
                  <li>Verifying the legal requirements in your jurisdiction</li>
                  <li>Proper service and delivery of legal notices</li>
                  <li>Compliance with all applicable laws and regulations</li>
                  <li>Any consequences resulting from the use of generated documents</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">Limitation of Liability</h2>
                <p className="text-muted-foreground">
                  LegalNotice Pro, its owners, employees, and affiliates shall not be liable for any damages, losses, or
                  legal consequences arising from the use of our service or generated documents. This includes but is
                  not limited to direct, indirect, incidental, or consequential damages.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">Jurisdictional Variations</h2>
                <p className="text-muted-foreground">
                  Legal requirements for notices vary significantly between jurisdictions. Our templates are based on
                  general legal principles and may not comply with specific local, state, or federal requirements in
                  your area.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-foreground mb-4">Contact for Legal Matters</h2>
                <p className="text-muted-foreground">
                  For questions about this disclaimer or legal matters related to our service:
                  <br />
                  Email: legal@legalnoticepro.com
                  <br />
                  Phone: 1-800-LEGAL-01
                  <br />
                  <br />
                  <strong>For legal advice, please consult with a qualified attorney in your jurisdiction.</strong>
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
